name: Bug Report
description: Report something that isn't working as expected
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the problem.
      placeholder: The component crashes when clicking X...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Help us reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What you expected to happen.

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Paste relevant logs or include screenshots.
      placeholder: Paste error stack trace or drag a screenshot here.

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.0.3

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Browser
        - Node.js
        - React Native
        - Other
